apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: my-web-app

  template:
    metadata:
      name: my-web-app
      labels:
        app: my-web-app    
    spec:
      containers:
        - name: my-nginx-app
          image: abdelaziz79/test1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80